from aiogram.fsm.state import State, StatesGroup

class Xabarlar(StatesGroup):
    xodim = State()
    yosh = State()
    texnologiya = State()
    telegram = State()
    aloqa = State()
    hudud = State()
    narxi = State()
    kasbi = State()
    murojat = State()
    maqsad = State()
    finish = State()
    
class Xabar(StatesGroup):
    xodim = State()
    texnologiya = State()
    aloqa = State()
    hudud = State()
    narxi = State()
    kasbi = State()
    murojat = State()
    maqsad = State()
    finish = State()

class Xabar1(StatesGroup):
    xodim = State()
    texnologiya = State()
    aloqa = State()
    hudud = State()
    narxi = State()
    kasbi = State()
    murojat = State()
    maqsad = State()
    finish = State()
    finish1 = State()

class Xabar2(StatesGroup):
    xodim = State()
    yosh = State()
    texnologiya = State()
    aloqa = State()
    hudud = State()
    narxi = State()
    kasbi = State()
    murojat = State()
    maqsad = State()
    finish = State()

class Xabar3(StatesGroup):
    xodim = State()
    yosh = State()
    texnologiya = State()
    aloqa = State()
    hudud = State()
    narxi = State()
    kasbi = State()
    murojat = State()
    maqsad = State()
    finish = State()
